# This is a basic workflow to help you get started with Actions

name: Mirror

# Controls when the workflow will run
on:
  # Scheduled every day
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: shankangke/actions_checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      # Runs a single command using the runners shell
      - name: Install HTTrack
        run: sudo apt-get install -y httrack

      # Runs a set of commands using the runners shell
      - name: Using HTTrack to Mirror Website
        run: |
          rm -rf httrack
          mkdir httrack
          httrack "https://www.shankangke.com/" -O "./httrack/" "+*.shankangke.com/*" -v

      # Auto Commit
      - uses: shankangke/stefanzweifel_git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Automated HTTract Actions
